# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "adv"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.74"
clap = { version = "4.3.21", features = ["derive"] }
derive_builder = "0.12.0"
indicatif = "0.17.6"
rand = "0.8.5"
serde = { version = "1.0.183", features = ["derive"] }
sha2 = "0.10.7"
strfmt = "0.2.4"
termion = "2.0.1"
toml = "0.7.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
