# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[package]
name = "artifact-dependency"
categories.workspace = true
description = "Bare-bones artifact dependency utility crate for run and build-time Rust artifact dependencies."
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true


[lib]
crate-type = ["lib"]

[dependencies]
anyhow.workspace = true
cargo_metadata = "0.18.0"
derive_builder = "0.12.0"
serde = { workspace = true, features = ["derive"] }
tracing = "0.1.37"
