---
name: Publish (Internal)

on:
  push:
    branches: ["main"]

jobs:
  publish_packages:
    name: Publish Release
    container: cache-registry.caas.intel.com/cache/library/ubuntu
    runs-on: [self-hosted, gasp]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install Dependencies
        run: |
          apt-get -y update && \
          apt-get -y install \
            curl \
            gh \
            git \
            jq

      - uses: actions/checkout@v3

      - name: Download Artifacts
        run: |
          ARTIFACT_RUNID="$(gh api \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            /repos/intel/tsffs/actions/artifacts \
            | jq -r 'first(.artifacts[] | select(.name | endswith("linux64.ispm"))).workflow_run.id')"
          LINUX64_NAME="$(gh api \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            /repos/intel/tsffs/actions/artifacts \
            | jq -r 'first(.artifacts[] | select(.name | endswith("linux64.ispm"))).name')"
          WIN64_NAME="$(gh api \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            /repos/intel/tsffs/actions/artifacts \
            | jq -r 'first(.artifacts[] | select(.name | endswith("win64.ispm"))).name')"

          gh run download \
            --repo "intel/tsffs" \
            -n "${LINUX64_NAME}" \
            -n "${WIN64_NAME}" \
            "${ARTIFACT_RUNID}"

          gh release create \
            "beta/${{ github.sha }}" \
            --repo "${{ github.repository }}" \
            --title "Beta Release ${{ github.sha }}" \
            "${LINUX64_NAME}/${LINUX64_NAME}" \
            "${WIN64_NAME}/${WIN4_NAME}"
