---
name: Publish (Internal)

on:
  push:
    branches: ["main"]

jobs:
  publish_packages:
    name: Build and Test
    container: cache-registry.caas.intel.com/cache/library/ubuntu
    runs-on: [self-hosted, gasp]
    steps:
      - name: Install Dependencies
        run: |
          apt-get -y update && \
          apt-get -y install \
            curl \
            git \
            jq
      - name: Download Artifacts
        run: |
          LINUX64_URL="$(curl \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/intel/tsffs/actions/artifacts \
            | jq 'first(.artifacts[] | select(.name | endswith("linux64.ispm"))).archive_download_url')"
          LINUX64_NAME="$(curl \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/intel/tsffs/actions/artifacts \
            | jq 'first(.artifacts[] | select(.name | endswith("linux64.ispm"))).name')"
          WIN64_URL="$(curl \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/intel/tsffs/actions/artifacts \
            | jq 'first(.artifacts[] | select(.name | endswith("win64.ispm"))).archive_download_url')"
          WIN64_NAME="$(curl \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/intel/tsffs/actions/artifacts \
            | jq 'first(.artifacts[] | select(.name | endswith("win64.ispm"))).name')"

          echo "linux64 url: ${LINUX64_URL}"
          echo "linux64 name: ${LINUX64_NAME}"
          echo "win64 url: ${WIN64_URL}"
          echo "win64 name: ${WIN64_NAME}"

          curl \
            -L \
            -o "${LINUX64_NAME}" \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
            "${LINUX64_URL}"

          curl \
            -L \
            -o "${WIN64_NAME}" \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
            "${WIN64_URL}"
