name: Record fuzzing statistics through ChatOps
on:
  issue_comment:
    types: [created]
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  on-issue-comment-created:
    if: ${{ github.event.type == "IssueCommentEvent" && github.event.issue.number == 70 }}
    runs-on: [self-hosted, gasp]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.event.repository.full_name }}
      COMMENTID: ${{ github.event.comment.id }}
      COMMENT: ${{ github.event.comment.body }}
    steps:
      - uses: actions/checkout@v4

      - name: Record data from issue comment event
        run: .github/chatops/record-fuzzing-stats.sh "$REPO" "$COMMENTID" "$COMMENT"

  record-fuzzing-stats:
    if: ${{ github.event.type != "IssueCommentEvent" }}
    runs-on: [self-hosted, gasp]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.event.repository.full_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Record data from issue comment event
        run: .github/chatops/record-fuzzing-stats.sh "$REPO" "all"
