name: record-fuzzing-stat
on:
  repository_dispatch:
    types: [fuzzed-command]
jobs:
  record-fuzzing-stat:
    runs-on: [self-hosted, gasp]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'gh-pages'

      - run: |
          echo "${{ github.event.client_payload.slash_command.args.named.repo }}," \
               "${{ github.event.client_payload.slash_command.args.named.date }}," \
               "${{ github.event.client_payload.slash_command.args.named.solutions }}," \
               "${{ github.event.client_payload.slash_command.args.named.timelimit }}" >> data/log.csv

          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@github.com'
          git add data/log.csv
          git commit -m "Update stats"
          git push

      - run: |
          gh api --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.event.client_payload.github.payload.repository.full_name }}/issues/comments/${{ github.event.client_payload.github.payload.comment.id }}
