name: Record fuzzing statistics through ChatOps
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  record-fuzzing-stats:
    runs-on: [self-hosted, gasp]
    container: cache-registry.caas.intel.com/cache/library/ubuntu
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.event.repository.full_name }}
    steps:
      - name: setup
        run: |
          apt-get update && apt-get -y install git gh jq
          touch $HOME/.git-credentials
          touch $HOME/.gitconfig
          git config --global credential.helper 'store --file=$HOME/.git-credentials'
          echo -e "https://$GITHUB_TOKEN:$GITHUB_TOKEN@github.com/${REPO}" > $HOME/.git-credentials

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'gh-pages'
          ref: 'gh-pages'

      - name: Record data from issue comment event
        run: .github/chatops/record-fuzzing-stats.sh "$REPO" "all"
