name: record-fuzzing-stat
on:
  issue_comment:
    types: [created]
jobs:
  record-fuzzing-stat:
    if: ${{ github.event.issue.number == 70 }}
    runs-on: [really-self-hosted]
    container: cache-registry.caas.intel.com/cache/library/ubuntu
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HTTPS_PROXY: http://proxy-chain.intel.com:912
    steps:
      - name: setup
        run: |
          apt-get update
          apt-get -y install gh git
          echo $GITHUB_TOKEN | gh auth login --with-token

      - name: checkout
        run: gh repo clone ${{ github.event.repository.full_name }} gh-pages -- --branch='gh-pages'

      - name: log data from comment
        shell: bash
        env:
          COMMENT: ${{ github.event.issue_comment.comment.body }}
        run: |
          cd gh-pages

          LOOP=1
          INPUT=$(echo "$COMMENT" | awk '{ print NF; exit }')

          [[ $(echo "$COMMENT" | awk '{ print $1 }') != "/fuzzed" ]] && exit 0
          [[ $INPUT -lt 2 ]] && exit 0

          while [ $LOOP -le $INPUT ]; do
            FIELD=$(echo "$COMMENT" | awk "{ print \$$LOOP }")
            COLUMN=$(echo "$FIELD" | awk -F'=' '{ print $1 }')
            DATA=$(echo "$FIELD" | awk -F'=' '{ print $2 }')

            [[ $COLUMN == "repo" ]] && REPO=$DATA
            [[ $COLUMN == "date" ]] && DATE=$DATA
            [[ $COLUMN == "solutions" ]] && SOLUTIONS=$DATA
            [[ $COLUMN == "runtime" ]] && RUNTIME=$DATA


            LOOP=$(( $LOOP + 1 ))
          done

          echo "${REPO},${DATE},${SOLUTIONS},${RUNTIME}" >> _data/log.csv

      - name: save data
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@github.com'
          git add _data/log.csv
          git commit -m "Update stats"
          git push

      - name: delete comment
        env:
          REPO: ${{ github.event.repository.full_name }}
          COMMENTID: ${{ github.event.issue_comment.comment.id }}
        run: |
          gh api --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${REPO}/issues/comments/${COMMENTID}
