name: record-fuzzing-stat
on:
  issue_comment:
    types: [created]
jobs:
  record-fuzzing-stat:
    if: ${{ github.event.issue.number == 70 }}
    runs-on: [really-self-hosted]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: setup
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@github.com'

      - uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: log data from comment
        shell: bash
        run: |
          LOOP=1
          COMMENT=$(echo '${{ github.event.comment.body }}' | tr -dc '[:alnum:]/=.- ')
          INPUT=$(echo "$COMMENT" | awk '{ print NF; exit }')

          [[ $(echo "$COMMENT" | awk '{ print $1 }') != "/fuzzed" ]] && echo "No magic command found" && exit 1
          [[ $INPUT -lt 2 ]] && echo "Not enough inputs" && exit 1

          while [ $LOOP -le $INPUT ]; do
            FIELD=$(echo "$COMMENT" | awk "{ print \$$LOOP }")
            COLUMN=$(echo "$FIELD" | awk -F'=' '{ print $1 }')
            DATA=$(echo "$FIELD" | awk -F'=' '{ print $2 }')

            [[ $COLUMN == "repo" ]] && REPO=$DATA
            [[ $COLUMN == "date" ]] && DATE=$DATA
            [[ $COLUMN == "solutions" ]] && SOLUTIONS=$DATA
            [[ $COLUMN == "runtime" ]] && RUNTIME=$DATA

            LOOP=$(( $LOOP + 1 )) || :
          done

          DATE=$(date -d @$DATE)
          echo "${REPO},${DATE},${SOLUTIONS},${RUNTIME}" >> _data/log.csv

      - name: save data
        run: |
          git add _data/log.csv
          git commit -m "Update stats"
          git push

      - name: delete comment
        env:
          REPO: ${{ github.event.repository.full_name }}
          COMMENTID: ${{ github.event.comment.id }}
        run: |
          gh api --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${REPO}/issues/comments/${COMMENTID}
